language: python
python:
  - "3.6.5"
services:
  -postgresql
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c 'create database test_db;' -U postgres
script:
  - nosetests --with-coverage
  - coveralls
after_success:
 - coveralls
