"""empty message

Revision ID: 21296bba960b
Revises: 4739e54a0cc6
Create Date: 2018-04-07 16:14:37.822686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21296bba960b'
down_revision = '4739e54a0cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('confirm_password', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('businesses', sa.Column('business_owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'businesses', 'users', ['business_owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.drop_column('businesses', 'business_owner')
    op.drop_table('users')
    # ### end Alembic commands ###
