"""empty message

Revision ID: 8485fdd3e386
Revises: 21296bba960b
Create Date: 2018-04-11 22:02:01.174086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8485fdd3e386'
down_revision = '21296bba960b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirm_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirm_password', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
